name: rMain
description: Lootboxes, crates, and gkit plugin for HCRuins
author: Kenny
main: me.kenny.main.Main
version: 0.1
commands:
  main:
  gkit:
    aliases: [gkits]
  tpoffline:
    aliases: [teleportoffline]
  shortcut:
    aliases: [sc]