name: GalasticCore
description: Galastic HCF Core plugin
author: Kenny
main: me.kenny.galastic.Galastic
version: 0.1
commands:
  galastic:
  tpoffline:
    aliases: [teleportoffline]
  shortcut:
    aliases: [sc]